# Do not edit. Generated by the configure script.
export PATH:=/var/www/html/node-v20.0.0/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/usr/local
